### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by scoubix16** [nicoduj/homebridge-sepsadSecurity#5]
Doesn't seem to work anymore, any query from the plugin to the website times out and no information can be retrieved including sensor information. Worked fine up to a couple of weeks ago, there may have been some changes to the API used...I'm on Homebridge 1.5.0 and security system is EPS/Homiris.

**Comment by nicoduj** [comment]
Hi, yes I noticed that. Will try to make it work again asap, I think it is something due to a time stamp in request.

**Comment by nicoduj** [comment]
Ok, I did some digging, and they have added another layer of security (which is good), with certificate pinning to the client. Will try to reverse that, but will take some time .

**Comment by nicoduj** [comment]
should be ok with 0.2.0
